<Project Sdk="Microsoft.NET.Sdk">
	
	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<PackageId>Microsoft.PacketCapture.Converter</PackageId>
		<RootNamespace>Microsoft.PacketCapture.Converter</RootNamespace>
		<AssemblyName>Microsoft.PacketCapture.Converter</AssemblyName>
	</PropertyGroup>
	
	<ItemGroup>
		<PackageReference Include="NuGet.Build.Tasks.Pack" Version="6.14.0">
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="System.Diagnostics.EventLog" Version="9.0.9" />
	</ItemGroup>
	
</Project>