name: 'Build and Test'

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-ubuntu:
    name: Build and Test (Ubuntu)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
    - name: Setup .NET
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger trx --results-directory ./
    - name: Upload test results
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: ${{ !cancelled() }}
      with:
        name: dotnet-ubuntu-test-results
        path: ./*.trx
    - name: Test Report
      uses: dorny/test-reporter@df6247429542221bc30d46a036ee47af1102c451 # v2.7.0
      if: ${{ !cancelled() }}
      with:
        name: Test Report (Ubuntu)
        path: ./*.trx
        reporter: dotnet-trx
  build-test-windows:
    name: Build and Test (Windows)
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
    - name: Setup .NET
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger trx --results-directory ./
    - name: Upload test results
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: ${{ !cancelled() }}
      with:
        name: dotnet-windows-test-results
        path: ./*.trx
    - name: Test Report
      uses: dorny/test-reporter@df6247429542221bc30d46a036ee47af1102c451 # v2.7.0
      if: ${{ !cancelled() }}
      with:
        name: Test Report (Windows)
        path: ./*.trx
        reporter: dotnet-trx